export const data = [
  {
    id: 1,
    name: 'Zitella',
    scores: 'A',
    percentage: '91%',
    class: 'class-one',
  },
  {
    id: 2,
    name: 'Hedda',
    scores: 'A-',
    percentage: '87%',
    class: 'class-two',
  },
  {
    id: 3,
    name: 'Alleyn',
    scores: 'C+',
    percentage: '69%',
    class: 'class-two',
  },
  {
    id: 4,
    name: 'Vanda',
    scores: 'B+',
    percentage: '82.2%',
    class: 'class-one',
  },
  {
    id: 5,
    name: 'Darsey',
    scores: 'C',
    percentage: '63%',
    class: 'class-two',
  },
  {
    id: 6,
    name: 'Lutero',
    scores: 'D+',
    percentage: '54%',
    class: 'class-one',
  },
  {
    id: 7,
    name: 'Joshua',
    scores: 'A',
    percentage: '95%',
    class: 'class-two',
  },
  {
    id: 8,
    name: 'Dee dee',
    scores: 'A',
    percentage: '93%',
    class: 'class-one',
  },
  {
    id: 9,
    name: 'Aleece',
    scores: 'B',
    percentage: '77%',
    class: 'class-two',
  },
  {
    id: 10,
    name: 'Lucho',
    scores: 'A',
    percentage: '96%',
    class: 'class-two',
  },
  {
    id: 11,
    name: 'Jody',
    scores: 'D',
    percentage: '48%',
    class: 'class-one',
  },
  {
    id: 12,
    name: 'Amie',
    scores: 'F',
    percentage: '25%',
    class: 'class-one',
  },
  {
    id: 13,
    name: 'Vivian',
    scores: 'F',
    percentage: '40%',
    class: 'class-two',
  },
  {
    id: 14,
    name: 'Thia',
    scores: 'A-',
    percentage: '85%',
    class: 'class-one',
  },
  {
    id: 15,
    name: 'Neddie',
    scores: 'A-',
    percentage: '89%',
    class: 'class-two',
  },
  {
    id: 16,
    name: 'Cooper',
    scores: 'B+',
    percentage: '81%',
    class: 'class-one',
  },
  {
    id: 17,
    name: 'Malina',
    scores: 'A-',
    percentage: '86%',
    class: 'class-two',
  },
  {
    id: 18,
    name: 'Hamilton',
    scores: 'C-',
    percentage: '57%',
    class: 'class-one',
  },
  {
    id: 19,
    name: 'Elias',
    scores: 'B-',
    percentage: '71%',
    class: 'class-two',
  },
  {
    id: 20,
    name: 'Fran',
    scores: 'F',
    percentage: '30%',
    class: 'class-one',
  },
];
